contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #dnanexusdataaccesstest channel"
    url: https://nfcore.slack.com/channels/dnanexusdataaccesstest
    about: Discussion about the nf-core/dnanexusdataaccesstest pipeline
